class JobErrorCode:
    INPUT_INVALID = "INPUT_INVALID"
    TOKEN_SCRAPE_FAILED = "TOKEN_SCRAPE_FAILED"
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_RESPONSE_INVALID = "PROVIDER_RESPONSE_INVALID"
    AUDIO_MERGE_FAILED = "AUDIO_MERGE_FAILED"
    STORAGE_WRITE_FAILED = "STORAGE_WRITE_FAILED"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
